### ISSUE TITLE
garnix.yaml fails without the exclude bit

### ISSUE THREAD

**Issue by zimbatm** [garnix-io/issues#18]
```yaml
builds:
  include:
    - 'legacyPackages.x86_64-linux.*'
    - 'devShell.x86_64-linux'
```
It looks like it's expecting the exclude to be present:

```
DecodeConfigError {message = "Aeson exception:\nError in $: \n Previous branch failure: Error in $.builds: key "exclude" not found\nexpected Null, but encountered Object"}
```
