### ISSUE TITLE
Option to disable sandbox?

### ISSUE THREAD

**Issue by srid** [garnix-io/issues#33]
Is there/ will there be a way to disable sandbox on certain flake outputs? 

For eg., `--option sandbox false` would allow https://github.com/srid/haskell-flake/issues/21 to pass in CI.

So far I've been excluding it in garnix.yaml:

```yaml
builds:
  exclude:
    # https://github.com/srid/haskell-flake/issues/21
    - "checks.*.default-hls"
```
