### ISSUE TITLE
Allow to specify rules for when to run/skip certain builds 

### ISSUE THREAD

**Issue by gvolpe** [garnix-io/issues#54]
With GHA one can configure when not to run the job according to certain rules, e.g.

```yaml
name: NixOS

on:
  pull_request:
    paths-ignore:
      - 'home/**'
  push:
    branches:
      - master
    paths-ignore:
      - '.git-crypt/**'
      - '.gitattributes'
      - '.gitignore'
      - 'home/**'
      - 'outputs/home-conf.nix'
      - 'outputs/ci.nix'
      - 'switch'
      - '.mergify.yml'
```

It would be great if we could configure similar rules in the `garnix.yaml` file to avoid (unnecessarily) triggering certain jobs. E.g.

```yaml
builds:
 global-paths-ignore:
   - '.mergify.yml'
   - 'README.md'
 exclude: []
 include:
 - job: '*.x86_64-linux.*'
   paths-ignore: 
     - 'system/**'
 - job: 'nixosConfigurations.dell-xps'
   paths-ignore: 
     - 'home/**'
 - job: 'nixosConfigurations.tongfang-amd'
   paths-ignore: 
     - 'home/**'
```

WDYT?
