### ISSUE TITLE
Garnix silent on incorrect config (unknown fields)

### ISSUE THREAD

**Issue by sellout** [garnix-io/issues#56]
I had a config that looked like
```yaml
build:
  exclude: []
  include:
    - '*.aarch64-darwin.*'
    - '*.aarch64-darwin'
    - '*.x86_64-linux.*'
    - '*.x86_64-linux'
    - 'nixosConfigurations.*'
```
Totally valid YAML, but the bug in the config is that it has `build:` not `builds:`.

Since this is a garnix-specific yaml, it might be fine to error when there’s extra stuff, but even just a warning that there were entries that garnix isn’t aware of (much like how `nix flake check` warns of unknown outputs) would be helpful in understanding why the build isn’t doing what one expects.
