### ISSUE TITLE
Is it possible to build darwinConfigurations?

### ISSUE THREAD

**Issue by axeltlarsson** [garnix-io/issues#90]
I tried including it in my garnix.yaml like so:

```
builds:
  exclude: []
  include:
  - '*.x86_64-linux.*'
  - defaultPackage.x86_64-linux
  - devShells.x86_64-linux
  - homeConfigurations.*
  - nixosConfigurations.*
  - darwinConfigurations.*
```

but unfortunately it doesn't seem to trigger. It would be amazing if it was possible!
